# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TEST CI

name: CI Build User Interface

on:
  push:
    branches:
      - develop
jobs:
  build:
    env:
      PUBLIC_URL: https://develop-water.corps.cloud
      REACT_APP_SHOW_LOGIN: yes
      REACT_APP_AUTH_HOST: https://develop-auth.corps.cloud/auth
      REACT_APP_AUTH_REDIRECT_URL: https://develop-water.corps.cloud
      REACT_APP_CUMULUS_API_URL: https://develop-cumulus-api.rsgis.dev
      REACT_APP_SHARED_API_URL: https://develop-shared-api.rsgis.dev
      REACT_APP_WATER_API_URL: https://develop-water-api.corps.cloud
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        if: ${{ always() }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CASTLECI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CASTLECI_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CASTLECI_AWS_REGION }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: Deploy to Dev
        env:
          AWS_REGION: ${{ secrets.CASTLECI_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CASTLECI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CASTLECI_AWS_SECRET_ACCESS_KEY }}
          CASTLECI_S3_BUCKET_APPS_DEVELOP: ${{ secrets.CASTLECI_S3_BUCKET_APPS_DEVELOP }}
        run: npm run deploy-develop
