# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# TEST CI

name: CI Build User Interface

on:
  push:
    branches:
      - stable
jobs:
  build:
    env:
      PUBLIC_URL: https://water.corps.cloud
      REACT_APP_SHOW_LOGIN: no
      REACT_APP_AUTH_HOST: https://auth.corps.cloud/auth
      REACT_APP_AUTH_REDIRECT_URL: https://water.corps.cloud
      REACT_APP_CUMULUS_API_URL: https://cumulus-api.rsgis.dev
      REACT_APP_SHARED_API_URL: https://shared-api.rsgis.dev
      REACT_APP_WATER_API_URL: https://water-api.rsgis.dev
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

      - name: Deploy to Stable
        env:
          AWS_DEFAULT_REGION: ${{ secrets.CASTLECI_AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CASTLECI_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CASTLECI_AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy-stable
